### ISSUE TITLE
Config driven template generation

### ISSUE THREAD

**Issue by aaronwalker** [cfndsl/cfndsl#117]
@aaronwalker This is great, been thinking (Not for this PR) but it could be better if you were able to define a `.cfndsl.yml` config in your project directory which could look like:

``` yaml
extras: "default_extras.yml"
templates:
  component_one:
    filename: "component_one/template.json"
    extras: "component_one/extras.yml"
    output: "stacks/component_one.json"
```

You then just run cfndsl and it'll generate the templates based on this configuration (Bonus of having default extras at the top then each template can override and have it's own extras).

With the identifier as the key for the config, you could also just generate one component by doing something like:

`cfndsl -c component_one`

(Would have to look at the best way of handling this to keep backwards compatibility)

**Comment by aaronwalker** [comment]
Additional to this type of support would be to render multiple template from a single cfndsl call.

Originally I was thinking something a simple a file name globbing
```
cfndsl -o output/ templates/*.rb
```
where the templates directory contains multiple templates and it will generate a corresponding json file in the output directory.

With your idea it might be possible to combine this functionality will the ability to proivde overrides for a specific template but otherwise use the defaults something like

```
source: "templates/*.rb"
output: "stacks"
extras: "default_extras.yml"
templates:
  component_one:
    filename: "component_one/template.json"
    extras: "component_one/extras.yml"
    output: "stacks/component_one.json"
```

This would allow you to run something like
```
cfndsl -c
```
which would render all templates but component_one would use the overriden values or alternative if you passed name of the component it would just render that template and by default the component name could just be the file name minus extension.

@stevenjack Thoughts???
