### ISSUE TITLE
Metadata / AWS::CloudFormation::Interface support?

### ISSUE THREAD

**Issue by ervoiox** [cfndsl/cfndsl#357]
Does cfndsl support `AWS::CloudFormation::Interface` - this would make it a lot easier to view some of our templates on the AWS console. However its a bit unique from the standard resource...

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-interface.html

**Comment by gergnz** [comment]
Hi @ervoiox,

cfndsl doesn't support `AWS::CloudFormation::Interface` directly, but you can put any structure that's appropriate within [metadata](https://github.com/cfndsl/cfndsl#template-metadata).
e.g.
```ruby
CloudFormation do
  Metadata(
    'AWS::CloudFormation::Interface' =>
    {
      ParameterGroups: [
        {
          Label: { default: 'test' },
          Parameters: %w[x y]
        }
      ]
    }
  )
end
```

produces
```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: test
      Parameters:
      - x
      - y
```

Does that help?
