### ISSUE TITLE
VPCZoneIdentifier is always an array - 1.0.0.pre

### ISSUE THREAD

**Issue by gergnz** [cfndsl/cfndsl#428]
There is a regression that I need to come up with a small example of in 1.0.0.pre.

In an autoscaling group VPCZoneIdentifier is an array, but I have template which builds this array. CFNDSL wants to make this an array regardless, which means I end up with an array of arrays which then CloudFormation doesn't like.

/cc @lwoggardner

**Comment by gergnz** [comment]
```ruby
# frozen_string_literal: true

require 'cfndsl'

CloudFormation do
  params = {}
  external_parameters.each_pair do |key, val|
    key = key.to_sym
    params[key] = val
  end

  Parameter(:public) do
    Description 'Put the ECS Cluster in the Public space or App space'
    Type 'String'
    Default 'false'
  end

  Condition(
    :public, FnEquals(Ref(:public), 'true')
  )

  AutoScaling_AutoScalingGroup(:asg) do
    # rubocop:disable Metrics/LineLength
    VPCZoneIdentifier FnIf(:public, %w[a b c].map { |az| FnImportValue(FnJoin('-', [FnSelect('0', FnSplit('-', Ref('AWS::StackName'))), 'vpc', "publicsubnet#{az}"])) }, %w[a b c].map { |az| FnImportValue(FnJoin('-', [FnSelect('0', FnSplit('-', Ref('AWS::StackName'))), 'vpc', "appsubnet#{az}"])) })
    # rubocop:enable Metrics/LineLength
  end
end
```

command:
```bash
cfndsl x.rb -f yaml
```


0.17.4:
```yaml
Resources:
  asg:
    Properties:
      VPCZoneIdentifier:
        Fn::If:
        - public
        - - Fn::ImportValue:
```

1.0.0.pre
```yaml
Resources:
  asg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - Fn::If:
        - public
        - - Fn::ImportValue:
```

not that 0.17.4 does not wrap VPCZoneIdentifier in an array, but 1.0.0.pre does.
